### ISSUE TITLE
Manifest validation task in gulpfile hits TypeError when validating mail manifest

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#134]
The `validate-forstore` task seems to look for a `DefaultSettings` element under `OfficeApp`, but in an Outlook add-in there is no `DefaultSettings` element. This causes the error:

```
[09:33:26] 'validate-forstore' errored after 21 ms
[09:33:26] TypeError: Cannot read property '0' of undefined
    at C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\gulpfile.js:65:47
    at Parser.<anonymous> (C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\node_modules\xml2js\lib\xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\node_modules\xml2js\lib\xml2js.js:445:26)
    at emit (C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\node_modules\sax\lib\sax.js:639:35)
    at emitNode (C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\node_modules\sax\lib\sax.js:644:5)
    at closeTag (C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\node_modules\sax\lib\sax.js:903:7)
    at Object.write (C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\node_modules\sax\lib\sax.js:1444:13)
    at Parser.exports.Parser.Parser.parseString (C:\Users\jasonjoh\Source\Repos\mail-addins\yo-scratch\node_modules\xml2js\lib\xml2js.js:503:31)
```

The offending line:

`if (manifestJson.OfficeApp.DefaultSettings[0].SourceLocation[0].$.DefaultValue.indexOf('https://') !== 0) {`

**Steps to repro:**
1. Run `yo office`, accepting all defaults. (This generates an HTML/CSS/JS mail addin).
2. Run `gulp validate --xmlfile manifest-my-office-project.xml`

**Comment by waldekmastykarz** [comment]
Good catch :smile:

**Comment by gavinbarron** [comment]
There's a simple fix that just checks the DefaultLocation of the first Form element found in the manifest and ensures that it uses https.

The down side is that a Mail App can have multiple forms i.e. ItemRead and ItemEdit.

**Comment by gavinbarron** [comment]
#143 addresses this

**Comment by jthake** [comment]
Thanks @gavinbarron . I need to review  a bunch of PRs and will get to this hopefully next week.
