### ISSUE TITLE
Mail Add-in: validate-forstore assumes /index.html exists

### ISSUE THREAD

**Issue by gavinbarron** [OfficeDev/generator-office#144]
In mail add-in the index.html files are not in the app root directory but are in folders for appread and appcompose. This causes the validate task to fail with an 

`[16:40:31] Error: ENOENT: no such file or directory, open 'C:\dev\mail-app\index.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Gulp.<anonymous> (C:\dev\mail-app\gulpfile.js:97:18)
    at module.exports (C:\dev\mail-app\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\dev\mail-app\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\dev\mail-app\node_modules\orchestrator\index.js:214:10)
    at C:\dev\mail-app\node_modules\orchestrator\index.js:279:18
    at finish (C:\dev\mail-app\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (C:\dev\mail-app\node_modules\orchestrator\lib\runTask.js:60:3)`

**Comment by gavinbarron** [comment]
Added behavior in #143 that looks at the specific index.html files that exist in the generated project and checks those for the use of the hosted version of Office.js

**Comment by jthake** [comment]
Thanks @gavinbarron . I need to review a bunch of PRs and will get to this hopefully next week.

**Comment by gavinbarron** [comment]
Closed with merge of #143
