### ISSUE TITLE
Beta: Compile error in Outlook add-in

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/generator-office#202]
In a new Outlook add-in project using TypeScript, I get the following compile error when running it with `npm start`:

“src/app.ts(15,11): error TS2304: Cannot find name ‘Outlook’.”

Options to create project:

```
yo office
? Would you like to create a new subfolder for your project? No
? What do you want to name your add-in? My Office Add-in
? Which Office client application would you like to support? Outlook
? Would you like to create a new project? Yes, I want a new project.
? Would you like to use TypeScript? Yes
? Choose a framework: Jquery
```

**Comment by erlangsec** [comment]
Possibly related: I got this error when trying to create new Outlook add-in:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-office/generators/app/templates/manifest/Outlook.xml
    at EditionInterface.exports.copy (/usr/lib/node_modules/generator-office/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (/usr/lib/node_modules/generator-office/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at constructor.copyFiles (/usr/lib/node_modules/generator-office/generators/app/index.js:251:21)
    at Object.<anonymous> (/usr/lib/node_modules/generator-office/node_modules/yeoman-generator/lib/index.js:408:23)
    at /usr/lib/node_modules/generator-office/node_modules/run-async/index.js:25:25
    at /usr/lib/node_modules/generator-office/node_modules/run-async/index.js:24:19
    at /usr/lib/node_modules/generator-office/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```

What fixed it for me, was to rename the template /app/templates/manifest/outlook.xml - to Outlook.xml (with a capital O). I assume the same works for the other templates as well.

I.e. there is a bug with locating the template files due to a mismatch in casing.

**Comment by jasonjoh** [comment]
Thanks @erlangsec! I think your issue is actually fixed by [this commit](https://github.com/OfficeDev/generator-office/commit/f549d4d7e229e6e6f67e3fc48ec98646d09fcb0c) and isn't directly related to the compile issue.

**Comment by beth-panx** [comment]
@erlangsec new package has been released with the commit that @jasonjoh referred to.
