### ISSUE TITLE
"Trying to copy from a source that does not exist" Error on case sensitive filesystem

### ISSUE THREAD

**Issue by schmir** [OfficeDev/generator-office#211]
Running yo office fails with "AssertionError: Trying to copy from a source that does not exist: /home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/generators/app/templates/manifest/Excel.xml"

This happens on a linux system and it looks like the cause is that generator-office assumes a case-insensitive filesystem. The above directory only contains a lowercase "excel.xml".

```
(local) ~/typed-xl % yo office                                                                    

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Office  │
    |--(o)--|    │   Add-in generator, by   │
   `---------´   │ @OfficeDev! Let's create │
    ( _´U`_ )    │    a project together!   │
    /___A___\   /╰──────────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Would you like to create a new subfolder for your project? No
? What do you want to name your add-in? My Office Add-in
? Which Office client application would you like to support? Excel
? Would you like to create a new add-in? Yes, I want a new add-in.
? Would you like to use TypeScript? Yes
? Choose a framework: Angular

For more information and resources on your next steps, we have created a resource.html file in your project.
? Would you like to open it now while we finish creating your project? Yes

----------------------------------------------------------------------------------

      Creating My office add-in add-in using ts and angular

----------------------------------------------------------------------------------



events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/generators/app/templates/manifest/Excel.xml
    at EditionInterface.exports.copy (/home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (/home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at constructor.copyFiles (/home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/generators/app/index.js:251:21)
    at Object.<anonymous> (/home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/node_modules/yeoman-generator/lib/index.js:408:23)
    at /home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/node_modules/run-async/index.js:25:25
    at /home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/node_modules/run-async/index.js:24:19
    at /home/ralf/opt/node-v6.9.5-linux-x64/lib/node_modules/generator-office/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by beth-panx** [comment]
Thanks! Fixed on master.
