### ISSUE TITLE
Error on startup when creating React Excel Add-in with Yeoman

### ISSUE THREAD

**Issue by ericklind** [OfficeDev/generator-office#385]
I'm trying to run the office setup for Excel using yo.  When I try to run the app, I get the following error:
```
$ npm start

> sift-addin@1.0.0 start C:\Users\ecloward.ODA\source\repos\sift.addin
> webpack-dev-server --inline --config config/webpack.dev.js --progress

C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:363
    throw err;
    ^

TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\lib\Server.js:114:49)
    at new Server (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\lib\Server.js:127:5)
    at startDevServer (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:355:14)
    at processOptions (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:309:5)
    at Object.<anonymous> (C:\Users\ecloward.ODA\source\repos\sift.addin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:424:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sift-addin@1.0.0 start: `webpack-dev-server --inline --config config/webpack.dev.js --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sift-addin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ecloward.ODA\AppData\Roaming\npm-cache\_logs\2018-11-27T00_32_57_505Z-debug.log

```
Please let me know how to resolve this or if there is a better way to get running.

**Comment by TCourtneyOwen** [comment]
@ericklind I will look into this today and see if there’s a general problem with the React template and get back to you. 

Thanks for reporting this issue.

**Comment by TCourtneyOwen** [comment]
@ericklind I just created a React Excel add-in with the latest version of generator-office, and "npm start" succeeds and the add-in works.  Can you please try running the following to ensure you have the latest version of generator office installed (the latest version is **1.1.19**):

"npm view generator-office version"

Also, can you please let us know which OS you are running this on (Windows, Mac, Linux)?

Thanks,

Courtney

**Comment by ericklind** [comment]
I figured out a little of what happened. NPM gave me a notice the webpack version was a security risk. Up updated it, and then everything crashed. I created a new project and it worked. You may want to look into why that is the case.

**Comment by akrantz** [comment]
This should work with the latest version 1.1.23. Please try it.

**Comment by TCourtneyOwen** [comment]
@ericklind Closing this issue since this is no longer a problem in the latest version of generator-office
