### ISSUE TITLE
While add-in is running, saving js changes causes rebuild to fail

### ISSUE THREAD

**Issue by slabereemsft** [OfficeDev/generator-office#392]
Steps to reproduce:
yo office
Choose react.js, typescript, excel add-in
npm run start
npm run sideload
while the add-in is running, open App.tsx and change             range.format.fill.color = 'yellow'; from yellow to green. hit ctrl+S.

Expected Result: Rebuild and add-in update
Actual result:
C:\dev\TestAddinAlpha\node_modules\ts-loader\dist\watch-run.js:18
        var times = watching.compiler.fileTimestamps;
                                      ^

TypeError: Cannot read property 'fileTimestamps' of undefined
    at C:\dev\TestAddinAlpha\node_modules\ts-loader\dist\watch-run.js:18:39
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\dev\TestAddinAlpha\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook (C:\dev\TestAddinAlpha\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._go (C:\dev\TestAddinAlpha\node_modules\webpack\lib\Watching.js:40:32)
    at Watching._invalidate (C:\dev\TestAddinAlpha\node_modules\webpack\lib\Watching.js:165:9)
    at watcher.compiler.watchFileSystem.watch (C:\dev\TestAddinAlpha\node_modules\webpack\lib\Watching.js:136:10)
    at Watchpack.watcher.once (C:\dev\TestAddinAlpha\node_modules\webpack\lib\node\NodeWatchFileSystem.js:59:4)
    at Object.onceWrapper (events.js:273:13)
    at Watchpack.emit (events.js:182:13)
    at Watchpack._onTimeout (C:\dev\TestAddinAlpha\node_modules\watchpack\lib\watchpack.js:144:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-addin-alpha@1.0.0 start: `webpack-dev-server --inline --config config/webpack.dev.js --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-addin-alpha@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\seanla\AppData\Roaming\npm-cache\_logs\2018-12-13T21_05_47_713Z-debug.log

**Comment by akrantz** [comment]
To resolve this, update to the latest version to ts-loader:
```
npm uninstall ts-loader
npm install -D ts-loader
```

**Comment by akrantz** [comment]
Fixed in https://github.com/OfficeDev/generator-office/releases/tag/v1.1.23.
