### ISSUE TITLE
Running office-generator fails with SSL error on Windows

### ISSUE THREAD

**Issue by MikaelUmaN** [OfficeDev/generator-office#484]
After installing node+npm, then yeoman, I am running:

`yo office`

The output:
```

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Office  │
    |--(o)--|    │   Add-in generator, by   │
   `---------´   │ @OfficeDev! Let's create │
    ( _´U`_ )    │    a project together!   │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Choose a project type: Office Add-in Task Pane project using React framework
? Choose a script type: JavaScript
? What do you want to name your add-in? addintest
? Which Office client application would you like to support? Excel

----------------------------------------------------------------------------------

      Creating ymer add-in for Excel using JavaScript and React at C:\dev\Excel\addintest

----------------------------------------------------------------------------------
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
PS C:\dev\Excel>
```

All versions are the latest available today (nodejs long term support version). I know the problem has something to do with my company using their own certificates. 

Usually I have to find the "trusted ca" file that yeoman or the generator uses and insert my company's ca there. But here I simply don't know what file to edit. I tried npm but no luck.

Could it be that the generator runs git commands? Any help appreciated.

**Comment by MoonRaker58** [comment]
run `node --help`

Near the end of the output is a section on Environment Variables. 
Here are some that may be of use:

`SSL_CERT_DIR    sets OpenSSL's directory of trusted certificates when used in conjunction with
                              --use-openssl-ca
SSL_CERT_FILE     sets OpenSSL's trusted certificate file when used in conjunction with
                              --use-openssl-ca`

And if you really want to use a sledgehammer to security:

`NODE_TLS_REJECT_UNAUTHORIZED  set to 0 to disable TLS certificate validation`

**Comment by TCourtneyOwen** [comment]
Thanks for getting in touch with us. The generator doesn’t use git (it used to), but it does download the project template from our GitHub repos as a zip file. However I’ve never seen a cert-related error during project generation. Just to be sure, can you please check and ensure you are running version 1.4.0 of generator-office, which we published a couple days ago?
