### ISSUE TITLE
"Command failed: wmic os get Caption" error when running yo office

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/generator-office#495]
I'm getting the aforementioned error when attempting to run yo office. I've freshly ran "npm install -g yo generator-office" before attempting this. Any ideas? The console output was as follows:

$ yo office
C:\Users\aljerabe\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: wmic os get Caption
ERROR:
Description = Unspecified error

    at makeError (C:\Users\aljerabe\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\aljerabe\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\aljerabe\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node_modules\windows-release\index.js:34:24)
    at osName (C:\Users\aljerabe\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node_modules\os-name\index.js:39:18)
    at new Insight (C:\Users\aljerabe\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node_modules\insight\lib\index.js:37:13)
    at Object.<anonymous> (C:\Users\aljerabe\AppData\Roaming\nvm\v8.11.3\node_modules\yo\lib\cli.js:54:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by TCourtneyOwen** [comment]
Can you please check and let me know the version of generator-office you are running? Also which version of NodeJs are you running?

**Comment by AlexJerabek** [comment]
Thanks for replying @TCourtneyOwen. Here are the versions of everything I'm running:
node: 8.11.3
yo: 3.1.0
generator-office: 1.4.0

**Comment by TCourtneyOwen** [comment]
I didn’t hit any issues the other day when running with Node 10.16.3 so it’s possible it’s an issue with older versions of NodeJs. There’s precedence for issues related to older versions of NodeJS. Can you please try updating your version of Node and see if that fixes it?

**Comment by AlexJerabek** [comment]
Updating did fix the issue. I'll close this. Thanks!
