### ISSUE TITLE
SSO not working for Outlook using TypeScript

### ISSUE THREAD

**Issue by isawek** [OfficeDev/generator-office#554]
i generated my project with "yo office" and selected the sso template and outlook.

after i had configured sso i tried to run the app but i get the following error:

Cannot find module 'html'
Error: Cannot find module 'html'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at Module.patchedRequire [as require] (C:\...\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/module.js:11:18)
    at new View (C:\...\node_modules\express\lib\view.js:81:14)
    at Function.render (C:\...\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\...\node_modules\express\lib\response.js:1012:7)
    at C:\...\node_modules\office-addin-sso\lib\app.js:57:21
    at Layer.handle [as handle_request] (C:\...\node_modules\express\lib\router\layer.js:95:5)

I tried npm install html but than an other error occured:

Module "html" does not provide a view engine.
Error: Module "html" does not provide a view engine.
    at new View (C:\...\node_modules\express\lib\view.js:84:13)
    at Function.render (C:\...\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\...\node_modules\express\lib\response.js:1012:7)
    at C:\...\node_modules\office-addin-sso\lib\app.js:57:21
    at Layer.handle [as handle_request] (C:\...\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\...\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\...\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\...\node_modules\express\lib\router\layer.js:95:5)
    at C:\...\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\...\node_modules\express\lib\router\index.js:335:12)

**Comment by TCourtneyOwen** [comment]
@isawek Sorry to hear you are having problems.  I just tried the Outlook SSO project and did not encounter any issues.  Can you please provide me with some additional details:

- Typescript or Javascript template?
- Outlook Desktop or Outlook Online
- Node version

Thanks,

Courtney

**Comment by isawek** [comment]
Typescript
Desktop
v8.9.4

**Comment by TCourtneyOwen** [comment]
Can you please try upgrading to Node v.12 or greater. I am not hitting any issue with v.v12.18.1

Thanks,

Courtney

**Comment by isawek** [comment]
doesnt work after the update. same issue

are there other prerequisites or should i reinstall something?

Thanks

**Comment by TCourtneyOwen** [comment]
Are you able to build the project by running "npm run build:dev" or does this fail as well?

**Comment by isawek** [comment]
yes, that works

**Comment by TCourtneyOwen** [comment]
And just to clarify, when you ran "npm run configure-sso" after creating the project, did that succeed?

**Comment by isawek** [comment]
yes it does.
it says "Application with id xxx successfully registered in Azure. ..."

**Comment by LouMM** [comment]
@isawek Can you provide a sample of code the reproduces with this issue? We can not reproduce this issue on our side. Let us know!
