### ISSUE TITLE
configure-sso: unable to set grant admin consent

### ISSUE THREAD

**Issue by Dylan-mts** [OfficeDev/generator-office#563]
Hello,

After creating an outlook add-in project with Yeoman, I tried to configure SSO with the command "npm run configure-sso" but I got the following error:

```
> office-addin-taskpane-sso-js@0.0.0 configure-sso C:\Source\AddInJs
> office-addin-sso configure manifest.xml

Opening browser for authentication to Azure. Enter valid Azure credentials
Login was successful!
Registering new application in Azure
Application was successfully registered with Azure
Setting identifierUri
Setting signin audience
Granting admin consent
(node:11784) UnhandledPromiseRejectionWarning: Error: Unable to set grant admin consent:
Bad Request({"ClassName":"Microsoft.Portal.Framework.Exceptions.ClientException","Message":"Graph call failed with httpCode=BadRequest, errorCode=Request_BadRequest, errorMessage=It looks like the application '9e604070-fa5e-4ee7-9fa4-c0f8800b9bc6' you are trying to use has been removed or is configured to use an incorrect application identifier., reason=Bad Request, correlationId = 5afa5737-e2e7-4d9d-bd88-79bee3d9a6b7, response = {\"odata.error\":{\"code\":\"Request_BadRequest\",\"message\":{\"lang\":\"en\",\"value\":\"It looks like the application '9e604070-fa5e-4ee7-9fa4-c0f8800b9bc6' you are trying to use has been removed or is configured to use an incorrect application identifier.\"},\"requestId\":\"7732599c-7282-4202-b629-31d0d977623d\",\"date\":\"2020-11-02T10:57:25\"}}","Data":{},"HResult":-2146233088,"XMsServerRequestId":null,"Source":null,"HttpStatusCode":400,"ClientData":{"errorCode":"Request_BadRequest","localizedErrorDetails":{"errorDetail":"It looks like the application '9e604070-fa5e-4ee7-9fa4-c0f8800b9bc6' you are trying to use has been removed or is configured to use an incorrect application identifier."},"operationResults":null,"timeStampUtc":"2020-11-02T10:57:25.3911204Z","clientRequestId":"5afa5737-e2e7-4d9d-bd88-79bee3d9a6b7","internalTransactionId":"a45d3bdf-c203-4d0e-a778-96fb88738749","tenantId":"85ca696b-47e9-4881-a172-a832ce9886ea","userObjectId":"2d583d3d-2728-485f-bf17-a7997d13f50b","exceptionType":"AADGraphException"}})

    at Object.<anonymous> (C:\Source\AddInJs\node_modules\office-addin-sso\lib\configure.js:69:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\Source\AddInJs\node_modules\office-addin-sso\lib\configure.js:4:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Yeoman configuration:

Type: Office-admin project supporting SSO
Language: TypeScript
Project Name: AddInTs
Office client app: Outlook
Node version v12.19.0, yo package 3.1.1, generator-office 1.7.5.

**Comment by TCourtneyOwen** [comment]
@Dylan-mts It's possible that there was an Azure outage when you ran "configure-sso."  Can you please try the operation again and see if the error still occurs?

Thanks,

Courtney

**Comment by Dylan-mts** [comment]
@TCourtneyOwen Despite several attempts, the error remains the same. We had to create a user in Azure with the role "Application administrator" to be able to run configure-sso, while we were using the "Global administrator" user.

**Comment by knaubw** [comment]
hi, i have exactly the same issue. Is there any news about it?

**Comment by TCourtneyOwen** [comment]
@knaubw are you running the "configure-sso" script under an account with tenant admin permissions (i.e when you logged in to the webpage that comes up, did you specify a user with tenant admin permissions)?  This shouldn't be required but it may help me to narrow down the problem.

Thanks,

Courtney
