### ISSUE TITLE
Outlook Add-in unable to start the dev server

### ISSUE THREAD

**Issue by wi18b078** [OfficeDev/generator-office#602]
Hi,

I am following this manual and I am unable to start the dev server.
[https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?view=outlook-js-preview&tabs=yeomangenerator](url)
 
I get the following message:

> The developer certificates have been generated in C:\Users\pol748\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate. Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

I tried the following command:
`npx office-addin-dev-certs install`
There are no space characters in the project folder name. I also tried to go to the directory and install the CA certificate manually but nothing works. 

You can find the log file below:
`0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\pol748\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'dev-server'
0 verbose cli ]
1 info using npm@7.5.2
2 info using node@v14.15.4
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\pol748\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:C:\Users\pol748\FirstOfficeAdd\.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:C:\Users\pol748\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\pol748\AppData\Roaming\npm\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 9ms
19 verbose npm-session 2e4e1b195c3aed94
20 timing npm:load Completed in 19ms
21 timing command:run-script Completed in 3045ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\pol748\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid office-addin-taskpane-js@0.0.1
24 verbose cwd C:\Users\pol748\FirstOfficeAdd
25 verbose Windows_NT 10.0.17763
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pol748\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev-server"
27 verbose node v14.15.4
28 verbose npm  v7.5.2
29 error code 1
30 error path C:\Users\pol748\FirstOfficeAdd
31 error command failed
32 error command C:\WINDOWS\system32\cmd.exe /d /s /c webpack-dev-server --mode development
33 verbose exit 1
`
Could you please help me resolve this issue?

**Comment by wi18b078** [comment]
[2021-02-05T14_39_27_916Z-debug.log](https://github.com/OfficeDev/generator-office/files/5933296/2021-02-05T14_39_27_916Z-debug.log)
