### ISSUE TITLE
Authorization_RequestDenied when running npm run configure-sso

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/generator-office#608]
# Expected behavior

`npm run configure-sso` to work...

# Current behavior

`npm run configure-sso` not working and returning the following error:

```
"code": "Authorization_RequestDenied",
"message": "Insufficient privileges to complete the operation."
```

## Steps to Reproduce

Execute `npm run configure-sso`

## Context

* Operating System: MacOS 11.2
* Node version: v10.16.0
* Office version: n/a
* Tool version: latest (updated today 20/2/21)

## Failure Logs

```
❯ npm run configure-sso

> office-addin-taskpane-sso@0.0.0 configure-sso /Users/seccial/Development/sidekick
> office-addin-sso configure manifest.xml

Opening browser for authentication to Azure. Enter valid Azure credentials
Login was successful!
Registering new application in Azure
(node:1252) UnhandledPromiseRejectionWarning: Error: Unable to register new application:
ERROR: Forbidden({
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "date": "2021-02-20T13:17:14",
      "request-id": "99bb6a68-d099-4cc9-98da-5f3b5ea8a894",
      "client-request-id": "99bb6a68-d099-4cc9-98da-5f3b5ea8a894"
    }
  }
})

    at Object.<anonymous> (/Users/seccial/Development/sidekick/node_modules/office-addin-sso/lib/configure.js:34:19)
    at Generator.throw (<anonymous>)
    at rejected (/Users/seccial/Development/sidekick/node_modules/office-addin-sso/lib/configure.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by leoseccia** [comment]
BTW: it works when I do it manually...

**Comment by leoseccia** [comment]
I was signing in with the wrong account... It works with my O365 Developer one.
