### ISSUE TITLE
 Cannot find module 'is-ci' on ubuntu

### ISSUE THREAD

**Issue by fhg-isi** [OfficeDev/generator-office#796]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x ] I am running the latest version of Node and the tools
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

# Expected behavior

When running

yo office 

I would expect no error.

# Current behavior

yo office
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'is-ci'
Require stack:
- /root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/node_modules/update-notifier/index.js
- /root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at lazy (/root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/node_modules/import-lazy/index.js:2:51)
    at /root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/node_modules/import-lazy/index.js:10:11
    at new UpdateNotifier (/root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/node_modules/update-notifier/index.js:46:4)
    at module.exports (/root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/node_modules/update-notifier/index.js:183:25)
    at updateCheck (/root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js:54:20)
    at Object.<anonymous> (/root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js:190:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/node_modules/update-notifier/index.js',
    '/root/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js'
  ]
}

Same for Node version v18.17:

yo office
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'is-ci'
Require stack:
- /root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/node_modules/update-notifier/index.js
- /root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/lib/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at lazy (/root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/node_modules/import-lazy/index.js:2:51)
    at /root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/node_modules/import-lazy/index.js:10:11
    at new UpdateNotifier (/root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/node_modules/update-notifier/index.js:46:4)
    at module.exports (/root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/node_modules/update-notifier/index.js:183:25)
    at updateCheck (/root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/lib/cli.js:54:20)
    at Object.<anonymous> (/root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/lib/cli.js:190:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/node_modules/update-notifier/index.js',
    '/root/.nvm/versions/node/v18.17.0/lib/node_modules/yo/lib/cli.js'
  ]
}

**Comment by Rick-Kirkham** [comment]
We don't recommend developing on Linux, unless you are sure that everyone who will use the add-in is also using Linux and accessing Office on the Web. See [Debug on Linux](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview#debug-on-linux). Given that, can we close this issue?

**Comment by millerds** [comment]
That is an error in yeoman and not the plugin.
